project_id = "mecotkulcgdbilaksddu"

[functions.deepseek-ai]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.recover-username]
verify_jwt = false

[functions.password-change-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.get-mapbox-key]
verify_jwt = false
